{{.TableResourceName}}AccessPolicy:
  Type: AWS::IAM::ManagedPolicy
  Properties:
    Description: !Sub
      - Grants CRUD access to the Dynamo DB table ${Table}
      - { Table: !Ref {{.TableResourceName}} }
    PolicyDocument:
      Version: 2012-10-17
      Statement:
        - Sid: DDBActions
          Effect: Allow
          Action:
          - dynamodb:BatchGet*
          - dynamodb:DescribeStream
          - dynamodb:DescribeTable
          - dynamodb:Get*
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:BatchWrite*
          - dynamodb:Create*
          - dynamodb:Delete*
          - dynamodb:Update*
          - dynamodb:PutItem
          Resource: !Sub ${ {{.TableResourceName}}.Arn}
        - Sid: DDBLSIActions
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Effect: Allow
          Resource: !Sub ${ {{.TableResourceName}}.Arn}/Index/*