pull_request_rules:
  - name: Merge on CI success and review approval
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - approved-reviews-by=@aws/aws-ecs-devx
      - -approved-reviews-by~=author
      - status-success=AWS CodeBuild us-west-2 (ecs-cli-v2-ci)
      - status-success=Semantic Pull Request
      - label!=WIP
      - -title~=(WIP|wip)
      - -merged
      - -closed
    actions:
      merge:
        method: squash
        strict: smart
        strict_method: merge