version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
      nodejs: 10
  build:
    commands:
       - cd $CODEBUILD_SRC_DIR
       - export GOPATH=/go
       - rm -rf cf-custom-resources/node_modules
       - mkdir -p /tmp/.aws
       - printf "[default]\nregion = us-west-2\n[profile e2etestenv]\nregion=us-west-1\n[profile e2eprodenv]\nregion=us-east-1\n" > /tmp/.aws/config
       - printf "[default]\naws_access_key_id=$E2E_USER_1_ACCESS_KEY\naws_secret_access_key=$E2E_USER_1_SECRET_KEY\n\n[e2etestenv]\naws_access_key_id=$E2E_USER_2_ACCESS_KEY\naws_secret_access_key=$E2E_USER_2_SECRET_KEY\n\n[e2eprodenv]\naws_access_key_id=$E2E_USER_3_ACCESS_KEY\naws_secret_access_key=$E2E_USER_3_SECRET_KEY\n" > /tmp/.aws/credentials
       - sed -i -e '$s/$/ --noColor/' e2e/e2e.sh
       - make build-e2e
       - docker build -t ecs-cli-v2/e2e . -f e2e/Dockerfile
       - docker run --privileged -v /tmp/.aws:/home/.aws -e "HOME=/home" ecs-cli-v2/e2e:latest
