HelloTable:
  Type: AWS::DynamoDB::Table
  Properties: 
    AttributeDefinitions: 
      - AttributeName: Name
        AttributeType: S
    KeySchema: 
      - AttributeName: Name
        KeyType: HASH
    ProvisionedThroughput: 
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5