# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: 2010-09-09
Description: Additional resources for application '{{.AppName}}'
Parameters:
{{range $line := .Parameters}}  {{$line}}
{{end}}
Resources:
{{range $line := .Resources}}  {{$line}}
{{end}}
Outputs:
{{range $line := .Outputs}}  {{$line}}
{{end}}