App:
  Type: String
  Description: Your application's name.
Env:
  Type: String
  Description: The environment name your service is being deployed to.
Service:
  Type: String
  Description: The name of the service being deployed.