# This YAML file defines the relationship and deployment ordering of your environments.

# The name of the pipeline
name: {{.Name}}

# The version of the schema used in this template
version: {{.Version}}

# This section defines the source artifacts.
source:
  # The name of the provider that is used to store the source artifacts.
  provider: {{.Source.ProviderName}}
  # Additional properties that further specifies the exact location
  # the artifacts should be sourced from. For example, the GitHub provider
  # has the following properties: repository, branch.
  properties:{{range $key, $value := .Source.Properties}}
    {{$key}}: {{$value}}{{end}}
{{$length := len .Stages}}{{if gt $length 0}}
# The deployment section defines the order the pipeline will deploy
# to your environments.
stages:{{range .Stages}}
    - # The name of the environment to deploy to.
      name: {{.Name}}
      # Optional: use test commands to validate this stage of your build.
      # test_commands: [echo 'running tests', make test]
{{end}}{{end}}
