TaskRole:
  Type: AWS::IAM::Role
  Properties:{{if .NestedStack}}{{$stackName := .NestedStack.StackName}}
    ManagedPolicyArns:{{range $managedPolicy := .NestedStack.PolicyOutputs}}
    - Fn::GetAtt: [{{$stackName}}, Outputs.{{$managedPolicy}}]{{end}}{{end}}
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: 'sts:AssumeRole'
    Policies:
      - PolicyName: 'DenyIAMExceptTaggedRoles'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: 'Deny'
              Action: 'iam:*'
              Resource: '*'
            - Effect: 'Allow'
              Action: 'sts:AssumeRole'
              Resource:
                - !Sub 'arn:aws:iam::${AWS::AccountId}:role/*'
              Condition:
                StringEquals:
                  'iam:ResourceTag/copilot-application': !Sub '${AppName}'
                  'iam:ResourceTag/copilot-environment': !Sub '${EnvName}'
