Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  WorkloadName:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
  # Customize your Aurora Serverless cluster by setting the default value of the following parameters.
  {{logicalIDSafe .Name}}DBName:
    Type: String
    Description: The name of the initial database to be created in the DB cluster.
    Default: {{.InitialDBName}}
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  {{logicalIDSafe .Name}}DBAutoPauseSeconds:
    Type: Number
    Description: The duration in seconds before the cluster pauses.
    Default: 1000
Mappings:
  {{logicalIDSafe .Name}}EnvScalingConfigurationMap: {{range $env := .Envs}}
    {{$env}}:
      {{- if eq $.Engine "MySQL"}}
      "DBMinCapacity": 1 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      "DBMaxCapacity": 8 # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256]
      {{- else}}
      "DBMinCapacity": 2 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      "DBMaxCapacity": 8 # AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384]
      {{end -}}
    {{end}}
Resources:
  {{logicalIDSafe .Name}}DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for Aurora cluster.
      SubnetIds:
        !Split [',', { 'Fn::ImportValue': !Sub '${App}-${Env}-PrivateSubnets' }]
  {{logicalIDSafe .Name}}SecurityGroup:
    Metadata:
      'aws:copilot:description': 'A security group for your workload to access the DB cluster {{logicalIDSafe .Name}}'
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'The Security Group for ${WorkloadName} to access DB cluster {{logicalIDSafe .Name}}.'
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
      Tags:
        - Key: Name
          Value: !Sub 'copilot-${App}-${Env}-${WorkloadName}-Aurora'
  {{logicalIDSafe .Name}}DBClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the database cluster.
      SecurityGroupIngress:
        {{- if eq .Engine "MySQL"}}
        - ToPort: 3306
          FromPort: 3306
        {{- else}}
        - ToPort: 5432
          FromPort: 5432
        {{- end}}
          IpProtocol: tcp
          Description: !Sub 'From the Aurora Security Group of the workload ${WorkloadName}.'
          SourceSecurityGroupId: !Ref {{logicalIDSafe .Name}}SecurityGroup
      VpcId:
        Fn::ImportValue:
          !Sub '${App}-${Env}-VpcId'
  {{logicalIDSafe .Name}}AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub Aurora main user secret for ${AWS::StackName}
      GenerateSecretString:
        {{- if eq .Engine "MySQL"}}
        SecretStringTemplate: '{"username": "admin"}'
        {{- else}}
        SecretStringTemplate: '{"username": "postgres"}'
        {{- end}}
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  {{- if .ParameterGroup}}
  # {{logicalIDSafe .Name}}DBClusterParameterGroup:
  #   Type: 'AWS::RDS::DBClusterParameterGroup'
  #   Properties:
  #     Description: !Ref 'AWS::StackName'
  #     Family: 'aurora-mysql5.7'
  #     Parameters:
  #       character_set_client: 'utf8'
  {{- else}}
  {{logicalIDSafe .Name}}DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      {{- if eq .Engine "MySQL"}}
      Family: 'aurora-mysql5.7'
      Parameters:
        character_set_client: 'utf8'
      {{- else}}
      Family: 'aurora-postgresql10'
      Parameters:
        client_encoding: 'UTF8'
      {{- end}}
  {{- end}}
  {{logicalIDSafe .Name}}DBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername:
        !Join [ "",  [ {{`'{{resolve:secretsmanager:'`}}, !Ref {{logicalIDSafe .Name}}AuroraSecret, ":SecretString:username}}" ]]
      MasterUserPassword:
        !Join [ "",  [ {{`'{{resolve:secretsmanager:'`}}, !Ref {{logicalIDSafe .Name}}AuroraSecret, ":SecretString:password}}" ]]
      DatabaseName: !Ref {{logicalIDSafe .Name}}DBName
      {{- if eq .Engine "MySQL"}}
      Engine: 'aurora-mysql'
      EngineVersion: '5.7.mysql_aurora.2.07.1'
      {{- else}}
      Engine: 'aurora-postgresql'
      EngineVersion: '10.12'
      {{- end}}
      EngineMode: serverless
      StorageEncrypted: true
      KmsKeyId:
        Fn::ImportValue:
          !Sub '${App}-ArtifactKey'
      DBClusterParameterGroupName: {{- if .ParameterGroup}} {{.ParameterGroup}} {{- else}} !Ref {{logicalIDSafe .Name}}DBClusterParameterGroup {{- end}}
      DBSubnetGroupName: !Ref {{logicalIDSafe .Name}}DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref {{logicalIDSafe .Name}}DBClusterSecurityGroup
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: !FindInMap [{{logicalIDSafe .Name}}EnvScalingConfigurationMap, !Ref Env, DBMinCapacity]
        MaxCapacity: !FindInMap [{{logicalIDSafe .Name}}EnvScalingConfigurationMap, !Ref Env, DBMaxCapacity]
        SecondsUntilAutoPause: !Ref {{logicalIDSafe .Name}}DBAutoPauseSeconds
  {{logicalIDSafe .Name}}SecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref {{logicalIDSafe .Name}}AuroraSecret
      TargetId: !Ref {{logicalIDSafe .Name}}DBCluster
      TargetType: AWS::RDS::DBCluster
Outputs:
  {{logicalIDSafe .Name}}Secret: # injected as {{logicalIDSafe .Name | toSnakeCase}}_SECRET environment variable by Copilot.
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'dbname', 'username', 'password'"
    Value: !Ref {{logicalIDSafe .Name}}AuroraSecret
  {{logicalIDSafe .Name}}SecurityGroup:
    Description: "The security group to attach to the workload."
    Value: !Ref {{logicalIDSafe .Name}}SecurityGroup

