Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
# Customize your Aurora Serverless cluster by setting the default value of these parameters. 
  DBTableName:
    Type: String
    Description: The name of the table.
    Default: mydatatable #{{.TableName}}
    # Cannot have special characters
    # Naming constraints: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  DBPort:
    Type: Number
    Description: The traffic port for connections to the database.
    Default: 5432 # Postgres
    # Default: 3306
  DBMinCapacity:
    Type: Number
    Description: The minimum scaling capacity for the cluster.
    AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384] # Postgres.
    # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256] # MySQL
    Default: 2 #{{.MinCapacity}}
  DBMaxCapacity:
    Type: Number
    Description: The maximum scaling capacity for the cluster.  
    AllowedValues: [2, 4, 8, 16, 32, 64, 192, 384] # Postgres.
    # AllowedValues: [1, 2, 4, 8, 16, 32, 64, 128, 256] # MySQL
    Default: 8 #{{.MaxCapacity}}
  DBAutoPauseSeconds:
    Type: Number
    Description: The duration in seconds before the cluster pauses.
    Default: 1000 #{{.TimeoutSeconds}}

Resources:
  AuroraKMSCMK:
    Type: 'AWS::KMS::Key'
    DeletionPolicy: Retain
    Properties:
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              StringEquals:
                'kms:CallerAccount': !Ref 'AWS::AccountId'
                'kms:ViaService': !Sub 'rds.${AWS::Region}.amazonaws.com'

  AuroraKMSCMKAlias:
    Type: 'AWS::KMS::Alias'
    DeletionPolicy: Retain
    DependsOn: ['AuroraDBCluster']
    Properties:
      AliasName: !Sub 'alias/${AuroraDBCluster}'
      TargetKeyId: !Ref AuroraKMSCMK

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Group of Copilot private subnets for Aurora cluster. 
      SubnetIds:
        !Split [',', { 'Fn::ImportValue': !Sub '${App}-${Env}-PrivateSubnets' }]

  DBClusterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: The Security Group for the database cluster. 
      SecurityGroupIngress:
        - ToPort: !Ref DBPort
          FromPort: !Ref DBPort
          IpProtocol: tcp
          Description: From Environment Security Group
          SourceSecurityGroupId: 
            Fn::ImportValue: 
              !Sub '${App}-${Env}-EnvironmentSecurityGroup'
      VpcId: 
        Fn::ImportValue: 
          !Sub '${App}-${Env}-VpcId'
      SecurityGroupEgress:
        - IpProtocol: '-1'
          Description: Allow all outbound traffic by default
          CidrIp: 0.0.0.0/0

  AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/${App}/${Env}/${Name}/${DBTableName}'
      Description: !Sub Aurora PostgreSQL main user secret for ${AWS::StackName}
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        ExcludePunctuation: true
        IncludeSpace: false
        PasswordLength: 16
  
  DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Description: !Ref 'AWS::StackName'
      Family: 'aurora-postgresql10'
      Parameters:
        client_encoding: 'UTF8'

  AuroraDBCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername:
        !Join [ "", [ "{{resolve:secretsmanager:", !Ref AuroraSecret, ":SecretString:username}}" ]]
      MasterUserPassword:
        !Join [ "", [ "{{resolve:secretsmanager:", !Ref AuroraSecret, ":SecretString:password}}" ]]
      DatabaseName: !Ref DBTableName
      Engine: aurora-postgresql # aurora-mysql
      EngineVersion: '10.7'
      EngineMode: serverless
      EnableHttpEndpoint: true
      StorageEncrypted: true
      KmsKeyId: !Ref AuroraKMSCMK
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBClusterSecurityGroup
      ScalingConfiguration:
        AutoPause: true
        MinCapacity: !Ref DBMinCapacity
        MaxCapacity: !Ref DBMaxCapacity
        SecondsUntilAutoPause: !Ref DBAutoPauseSeconds

  SecretAuroraClusterAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref AuroraSecret
      TargetId: !Ref AuroraDBCluster
      TargetType: AWS::RDS::DBCluster

Outputs:
  AuroraMetadata: # injected as AURORA_METADATA environment variable by Copilot. 
    Description: "The JSON secret that holds the database username and password. Fields are 'host', 'dbname', 'username', 'password'"
    Value: !Ref AuroraSecret