# DNS Delegation Resources
CertificateValidationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    Code:
      ZipFile: |
        {{.ACMValidationLambda}}
    Handler: "index.certificateRequestHandler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs10.x

DNSDelegationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    Code:
      ZipFile: |
        {{.DNSDelegationLambda}}
    Handler: "index.domainDelegationHandler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs10.x

# Resources to enable long ARN formats for the CF execution role.
EnableLongARNFormatFunction:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      ZipFile: |
        {{.EnableLongARNFormatLambda}}
    Handler: "index.handler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CloudformationExecutionRole.Arn'
    Runtime: nodejs10.x