VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: {{.CIDR}}
    EnableDnsHostnames: true
    EnableDnsSupport: true
    InstanceTenancy: default
    Tags:
      - Key: Name
        Value: !Sub 'copilot-${AppName}-${EnvironmentName}'

PublicRouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
    VpcId: !Ref VPC
    Tags:
      - Key: Name
        Value: !Sub 'copilot-${AppName}-${EnvironmentName}'

DefaultPublicRoute:
  Type: AWS::EC2::Route
  DependsOn: InternetGatewayAttachment
  Properties:
    RouteTableId: !Ref PublicRouteTable
    DestinationCidrBlock: 0.0.0.0/0
    GatewayId: !Ref InternetGateway

InternetGateway:
  Type: AWS::EC2::InternetGateway
  Properties:
    Tags:
      - Key: Name
        Value: !Sub 'copilot-${AppName}-${EnvironmentName}'

InternetGatewayAttachment:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
    InternetGatewayId: !Ref InternetGateway
    VpcId: !Ref VPC
{{range $ind, $cidr := .PublicSubnetCIDRs}}
PublicSubnet{{inc $ind}}:
  Type: AWS::EC2::Subnet
  Properties:
    CidrBlock: {{$cidr}}
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ {{$ind}}, !GetAZs '' ]
    MapPublicIpOnLaunch: true
    Tags:
      - Key: Name
        Value: !Sub 'copilot-${AppName}-${EnvironmentName}-pub{{$ind}}'
{{end}}{{range $ind, $cidr := .PrivateSubnetCIDRs}}
PrivateSubnet{{inc $ind}}:
  Type: AWS::EC2::Subnet
  Properties:
    CidrBlock: {{$cidr}}
    VpcId: !Ref VPC
    AvailabilityZone: !Select [ {{$ind}}, !GetAZs '' ]
    MapPublicIpOnLaunch: false
    Tags:
      - Key: Name
        Value: !Sub 'copilot-${AppName}-${EnvironmentName}-priv{{$ind}}'
{{end}}{{range $ind, $cidr := .PublicSubnetCIDRs}}
PublicSubnet{{inc $ind}}RouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
    RouteTableId: !Ref PublicRouteTable
    SubnetId: !Ref PublicSubnet{{inc $ind}}{{end}}