# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that represents a backend service on Amazon ECS.
Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  ServiceName:
    Type: String
  ContainerImage:
    Type: String
  ContainerPort:
    Type: Number
  TaskCPU:
    Type: String
  TaskMemory:
    Type: String
  TaskCount:
    Type: Number
  AddonsTemplateURL:
    Description: 'URL of the addons nested stack template within the S3 bucket.'
    Type: String
    Default: ""
  LogRetention:
    Type: Number
    Default: 30
Conditions:
  HasAddons:
    !Not [!Equals [!Ref AddonsTemplateURL, ""]]
Resources:
{{include "loggroup" . | indent 2}}

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
{{include "fargate-taskdef-base-properties" . | indent 6}}
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
{{include "envvars" . | indent 10}}
{{include "logconfig" . | indent 10}}
{{- if .HealthCheck}}
          HealthCheck:
            Command: {{quoteSlice .HealthCheck.Command | fmtSlice}}
            Interval: {{.HealthCheck.Interval}}
            Retries: {{.HealthCheck.Retries}}
            StartPeriod: {{.HealthCheck.StartPeriod}}
            Timeout: {{.HealthCheck.Timeout}}
{{- end}}
{{include "sidecars" . | indent 8}}
{{include "executionrole" . | indent 2}}

{{include "taskrole" . | indent 2}}

{{include "servicediscovery" . | indent 2}}

  Service:
    Type: AWS::ECS::Service
    Properties:
{{include "service-base-properties" . | indent 6}}
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: !Ref ContainerPort

{{include "addons" . | indent 2}}