name: ci

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: [compile-linux, compile-windows, compile-darwin]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Generate static files
        run: make packr-build

      - name: Build binaries
        run: make ${{matrix.command}}

      - name: Cleanup
        run: make packr-clean

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

  integ-test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CF_LINT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CF_LINT }}
          aws-region: us-west-2

      - name: Run tests
        run: make local-integ-test

  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34.1
          args: --timeout 5m0s

  license:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run license check
        run: ./scripts/license.sh .
